language: c

os: linux
dist: xenial

arch:
  - amd64
  - arm64
  - s390x
  - ppc64le

addons:
  apt:
    update: true
    packages: build-essential gdb

compiler:
  - gcc
  - clang

script: ci/segfault-demo.sh
# script: ci/named-pipe-segfalt-demo.sh


notifications:
  email: false
